// Autogenerated using the moz templater annotation.
//
//
package services

import "time"

var (
	// defaultSendWithBeforeAbort defines the time to await receving a message else aborting.
	defaultSendWithBeforeAbort = 3 * time.Second
)
